### ISSUE TITLE
Build failed with an exception while Building Apk

### ISSUE THREAD

**Issue by lohitbura07** [passbase/flutter-demo-app#7]
Getting Following error while building apk using flutter build apk command . But Its working fine in debug mode. 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':passbase_flutter:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/Users/unthinkble/Documents/MyProjects/MRGO/build/passbase_flutter/intermediates/merged_res/release/values/values.xml:6371: AAPT: error: resource android:attr/lStar not found.

passbase_flutter: ^3.2.1

Flutter 3.3.0 • channel unknown • unknown source
Framework • revision ffccd96b62 (7 weeks ago) • 2022-08-29 17:28:57 -0700
Engine • revision 5e9e0e0aa8
Tools • Dart 2.18.0 • DevTools 2.15.0

**Comment by skorostetskyi** [comment]
Hi @lohitbura07,
I am sorry you had to deal with that issue.

We have released a fix. Could you try:
- `passbase_flutter: ^2.13.7`   if you are using a Classic product
- `passbase_flutter_v3: ^3.5.1`   if you are using a Premium product

Please contact me if there are any problems.

**Comment by lohitbura07** [comment]
Hi @skorostetskyi 
I have Used the 2.13.7 version but I am now getting following error while using flutter run

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageDebug'.
> A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
   > java.lang.OutOfMemoryError (no error message)

**Comment by lohitbura07** [comment]
Hi @skorostetskyi 
Using 2.13.7 fixed the issue . Thanks, You just made my day.
